### ISSUE TITLE
Unattended comment

### ISSUE THREAD

**Issue by aleksandrenko** [RuslanNikolov/notification-itg#11]
https://github.com/RuslanNikolov/notification-itg/blob/9006963a5507f3699a7e7eddc52f960d7ce2407c/src/App/Notification/Message/Message.tsx#L19

Please check the comment and remove if a suggestion is already taken into considiration.

**Comment by RuslanNikolov** [comment]
Understand! Is notification-message okay?

**Comment by RuslanNikolov** [comment]
This will be no longer an issue when we introduce css modules.
