### ISSUE TITLE
UX thing

### ISSUE THREAD

**Issue by aleksandrenko** [RuslanNikolov/notification-itg#7]
https://github.com/RuslanNikolov/notification-itg/blob/9006963a5507f3699a7e7eddc52f960d7ce2407c/src/App/Notification/Notification.css#L36

This is technically correct. But it's not adding value to the UX. 
This is my fault. You were not given any UI requirement.

**Comment by RuslanNikolov** [comment]
Guess it's my fault, wanting to put some cool effects (that are subsequently not that good 😍)
