### ISSUE TITLE
Consistent units

### ISSUE THREAD

**Issue by aleksandrenko** [RuslanNikolov/notification-itg#8]
https://github.com/RuslanNikolov/notification-itg/blob/9006963a5507f3699a7e7eddc52f960d7ce2407c/src/App/Notification/Notification.css#L46

There are px and rems used for font-size. For consistency and predictability, it's a good idea to stick to the selected sizing unit.

**Comment by RuslanNikolov** [comment]
Yes, totally agree, forgot it there by accident.
