### ISSUE TITLE
overflow-x

### ISSUE THREAD

**Issue by aleksandrenko** [RuslanNikolov/notification-itg#9]
https://github.com/RuslanNikolov/notification-itg/blob/9006963a5507f3699a7e7eddc52f960d7ce2407c/src/App/Notification/Notification.css#L52

It's a good idea to define the overflow-x also, just to be sure it will behave good for any type of string. 
Try adding a very long string with no spaces, like a long url and see how the layout will behave.

**Comment by RuslanNikolov** [comment]
Gotcha! That long string really messed up the UI
